### ISSUE TITLE
Error while using terraform local-exec provisioner with manheim terraform pipeline

### ISSUE THREAD

**Issue by sujikann** [manheim/terraform-pipeline#167]
Issue description: Unable to use terraform local-exec provisioner with manheim terraform pipeline

* null_resource.install_python_dependencies: : invalid or unknown key: environment

Cause: Conflict on "environment" variable. The local-exec provisioner uses environment as a keyword and needs it declared as a "map" datatype variable. terraform-pipeline assumes environment and sets it up with the stage variable passed in Jenkinsfile
ex) def deployQa = new TerraformEnvironmentStage('qa')

Is there a way (maybe a plugin) to rename the "environment" variable to a different one, say "env" instead? 

```
resource "null_resource" "install_python_dependencies" {
  triggers {
    requirements = "${sha1(file("${var.source_code_path}/requirements.txt"))}"
    dir_hash     = "${data.archive_file.dir_hash_zip.output_base64sha256}"
  }

  provisioner "local-exec" {
    command = "bash ${path.module}/scripts/py_pkg.sh"

    environment = {
      source_code_path = "${var.source_code_path}"
      path_cwd         = "${path.cwd}"
      path_module      = "${path.module}"
      runtime          = "${var.runtime}"
      function_name    = "${var.function_name}"
      random_string    = "${random_string.name.result}"
    }
  }
}
```

**Comment by kmanning** [comment]
Hrm, the DefaultEnvironmentPlugin is the one that sets the TF_VAR_environment variable.  See: https://github.com/manheim/terraform-pipeline/blob/master/src/DefaultEnvironmentPlugin.groovy#L13

It seems like it would be pretty easy to make the variable name configurable.  If we were to go that route, it could look something like: 

```
DefaultEnvironmentPlugin.withVariableName('env')
```

That method could then overwrite the default `environment` name that's currently being used.

*BUT*: It's not clear that a variable name conflict is the source of your problem?  That error  should be reproducible  outside of  terraform-pipeline.  Eg: 

```
TF_VAR_environment terraform apply .
```

I can't reproduce the issue, and your code is only a snippet.  Could you  create a shareable piece of terraform code that I could run to reproduce the issue, so that we can confirm that this is a variable name  conflict problem?

**Comment by kmanning** [comment]
Could you also note the version of terraform  that you're using?

**Comment by kmanning** [comment]
No response to the questions above, and can't reproduce without more information.  

Please re-open, and provide code examples that can be used to reproduce the issue.
