### ISSUE TITLE
S3BackendPlugin: Inverted environment variable priority.

### ISSUE THREAD

**Issue by dkolb** [manheim/terraform-pipeline#176]
Currently, the "default" environment variables (S3_BACKEND_BUCKET, S3_BACKEND_REGION, S3_BACKEND_ENCRYPT) override the environment specific ones.  Take the following setup:

```
TerraformEnvironmentStage
  .withGlobalEnv('S3_BACKEND_BUCKET', 'terraform-secure-nonprodacct')
  .withGlobalEnv('S3_BACKEND_REGION', 'us-east-1')
  .withGlobalEnv('S3_BACKEND_ENCRYPT', 'true')
  .withGlobalEnv('PERF_S3_BACKEND_BUCKET', 'terraform-secure-prodacct')
  .withGlobalEnv('PROD_S3_BACKEND_BUCKET', 'terraform-secure-prodacct')
```

This will always pick a bucket of `terraform-secure-nonprodacct`.  This goes against most common convention for configuration: The more specific a configuration value, the higher it's priority.  Environment specific should override global, imo.  Unfortunately, we may just need to document this instead as it might break other folks who expect this behavior now.

**Comment by kmanning** [comment]
The scope of such a change would be larger than just the S3BackendPlugin.  Changing the priority of one of these plugins should mean changing the priority to match in all of them.

https://github.com/manheim/terraform-pipeline/blob/master//src/AwssumePlugin.groovy#L52-L64
https://github.com/manheim/terraform-pipeline/blob/master/src/CrqPlugin.groovy#L18-L26
https://github.com/manheim/terraform-pipeline/blob/master/src/S3BackendPlugin.groovy#L44-L61
https://github.com/manheim/terraform-pipeline/blob/master/src/WithAwsPlugin.groovy#L41-L57

--- 

The existence of `.withGlobalEnv` came after the creation of many of the plugins above.  The current priority was necessitated by the lack of  `.withGlobalEnv`.

The current docs offer the multiple options, but don't spell out the priority (I had a nagging feeling this would eventually bite me).  So that said, I don't think it's too late to change it.  We could consider making the priority toggle-able, as a stepping stone to deprecating/removing the existing priority.

**Comment by dkolb** [comment]
Honestly I don't think there is anything inherently wrong with the priority outside being less than ideal if you obsess over DRY'ing.  As someone who used to do that and produced a really obnoxious deployment framework that I deeply regret all to not repeat myself across a set of environments, I've learned my lesson.

I think we just need to document it and point it out so it doesn't cost someone 20 minutes and digging through the source code to realize. Lol.
