### ISSUE TITLE
CredentialsPlugin should be applied to every Stage, not just BuildStage

### ISSUE THREAD

**Issue by dkolb** [manheim/terraform-pipeline#192]
## Overview

Currently Credentials Plugin only supports the build stage and Username/Password credentail types.

The current use case I have requires mapping credentials onto TF_VAR_blah environment variables in the environment stages.  Furthermore, some of these credentials are of the `string()` type of DSL call.  Finally, some of these credentials differ between individual environment stage.

## Current Workarounds

Currently I'm moving to decorating each stage directly in the Jenkinsfile for now.

```groovy
def validate   = new TerraformValidateStage()
def deployDev  = new TerraformEnvironmentStage('dev')

deployDev.decorate(TerraformEnvironmentStage.ALL, { closure ->
  withCredentials([
    usernamePassword(
      credentialsId: 'some-user'
      usernameVariable: 'TF_VAR_some_user',
      passwordVariable: 'TF_VAR_some_passord'
    ),
    string(
      credentialsId: 'some-secret',
      variable: 'TF_VAR_some_secret'
    )
  ]) {
    closure()
  }
})

validate
  .then(deployDev)
  .build()
```

**Comment by brobbins0** [comment]
+1 - Need to be able to use CredentialsPlugin on RegressionStage

**Comment by kmanning** [comment]
This sounds like at least 2 separate issues: 
1.  CredentialsPlugin should be available to every Stage
2. It should be possible to set unique credentials for  different instances of a Stage. 

I'll use this Issue to tackle point 1, then split off a separate Issue for point 2.

**Comment by kmanning** [comment]
Of the 3 issues outlined above, the first is taken care of with the above PR/Merge.

Thinking through the second (unique credentials per Environment), that seems a little tricky.  There's already a "pattern"  for environment-specific  configuration for plugins like the S3BackendBucket, but I don't think that pattern fits well with the UseCase here.

I'm gonna break 2 and 3 out into separate issues, so that the first (CredentialsPlugin  should be  applied to every Stage) can be released sooner.
