### ISSUE TITLE
Auto-convert git/ssh-urls to https with GithubPRPlanPlugin

### ISSUE THREAD

**Issue by jleopold28** [manheim/terraform-pipeline#254]
When attempting to clone an https repository (`https://github.com/blah/foo`), the pipeline actually pulls via the git protocol (`git://github.com/blah/foo`).

This causes a problem when we execute the curl command to post comments. 
See:
```
+ curl -H 'Authorization: token ****' -X POST -d @/home/jenkins/workspace/_terraform-pipeline-example_PR-4@tmp/body.txt -H 'Content-Type: application/json' -D comment.headers git://github.com/api/v3/repos/foo/terraform-pipeline-example/issues/4/comments
curl: (1) Protocol git not supported or disabled in libcurl
```

**Comment by kmanning** [comment]
It looks like you're using the GithubOrg jenkins plugin, and you've added behavior to "Checkout over SSH".  As a result, the git url that the plugin is finding has the `git://` protocol instead of an `https://` protocol.

**Comment by kmanning** [comment]
I think there are 2 possible options here:
1. We can advertise the `withRepoHost()` method, and you can override the github URL that is being used to check the project out.
2. We can auto-magically check and replace the `git://` protocol with `https://`.  <-- I think this is opening up a can of worms.  Since the user chose to check the repo out with SSH, we don't know if their github instance is available over http or https.

**Comment by kmanning** [comment]
Have we validated that the PR link is constructed correctly for the public github?

**Comment by kmanning** [comment]
Bumping this to v5.10, so we can cut a v5.9 release

**Comment by jleopold28** [comment]
> Have we validated that the PR link is constructed correctly for the public github?

You mean posting the plan results to public github? I remember testing that when we did the initial release
