### ISSUE TITLE
Support Jenkins Credentials parameters in TerraformEnvironmentStage

### ISSUE THREAD

**Issue by kmanning** [manheim/terraform-pipeline#92]
* Allow credentials to be used in the TerraformEnvironmentStage
* Need to think through this a bit:
    * UseCase: Global credentials like artifactory - easy
    * UseCase: environment-specific credentials - what do we do here?

**Comment by kmanning** [comment]
See Issue #192 
See Issue  #213

**Comment by dkolb** [comment]
At the risk of being less DRY perhaps credentials and environment variables should be a first-class object you apply to a particular stage instance rather than a plugin?

It seems mapping various "things" into the environment of each stage is something that needs to be directly supported through a common interface on the stages themselves than being deferred to the plugin system.
